package(default_visibility = ["//visibility:public"])

cc_library(
    name = "sys_tick",
    srcs = ["sys_tick.cc"],
    hdrs = ["public/sys_tick/sys_tick.h"],
    includes = ["public/"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/bsp/atsame54n20a:peripheral",
    ],
)
