cc_library(
    name = "sqr_wave",
    srcs = ["sqr_wave.cc"],
    hdrs = ["public/sqr_wave/sqr_wave.h"],
    includes = ["public/"],
    visibility = ["//visibility:public"],
    deps = [
        "@atsame54_device_pack//:same54n20a_deps",
        "@pigweed//pw_log",
    ],
)
