cc_library(
    name = "sqr_wave",
    srcs = ["sqr_wave.cc"],
    hdrs = ["public/sqr_wave/sqr_wave.h"],
    includes = ["public/"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/bsp/atsame54n20a:peripheral",
        "//src/bsp/wrapper/gpio",
        "@pigweed//pw_log",
    ],
)
